apiVersion: v1
kind: LimitRange
metadata:
  name: limit-mem-cpu-per-container
spec:
  limits:
  - max:
      cpu: "6000m"
      memory: "3Gi"
    min:
      cpu: "100m"
      memory: "99Mi"
    default:
      cpu: "1000m"
      memory: "1Gi"
    defaultRequest:
      cpu: "110m"
      memory: "111Mi"
    type: Container
