apiVersion: v1
kind: LimitRange
metadata:
  name: limit-mem-cpu-per-container
spec:
  limits:
  - max:
      cpu: "4000m"
      memory: "1500Mi"
    min:
      cpu: "100m"
      memory: "99Mi"
    default:
      cpu: "1000m"
      memory: "1Gi"
    defaultRequest:
      cpu: "200m"
      memory: "100Mi"
    type: Container
