kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ui-base-role
rules:
- apiGroups:
  - "" 
  resources:
  - namespaces
  - persistentvolumes
  - persistentvolumeclaims
  verbs:
  - get
  - list
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list

