kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: role-read
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - events
  - replicationcontrollers
  - resourcequotas
  - limitranges
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - extensions
  - apps
  resources:
  - deployments
  - daemonsets
  - statefulsets
  - ingresses
  - replicasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - list
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - get
  - watch
  - list
