apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-sa
  namespace: default
  labels:
    auth-token: zaqwsx

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: sa:role:read:prd:demo-sa
  namespace: prd
subjects:
- kind: ServiceAccount
  name: demo-sa
  namespace: default
roleRef:
  kind: Role
  name: role-read
  apiGroup: rbac.authorization.k8s.io

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sa:cluster-role:ui:demo-sa
subjects:
- kind: ServiceAccount
  name: demo-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: ui-base-role
  apiGroup: rbac.authorization.k8s.io
