apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        log
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          upstream
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . 202.101.172.35:53 202.101.172.47:53 8.8.8.8:53 {
          policy round_robin
          prefer_udp
        }
        cache 30
        loop
        reload
        loadbalance
    }
    worken.cn {
        errors
        cache 30
        forward . 192.168.20.8
    }
    worken.net {
        errors
        cache 30
        forward . 192.168.20.32
    }
